# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5332d76fbe53a65ad429706bb4d508cb773d0ce7c505009b6802ccf737e7abe2168930281665f472783b53a8f59ebe92be828bd91ff0e4c8ce19059ad784124e

test:
  secret_key_base: b291e461adeb8e454809842825486889954ed474c762ee3be7655f8e248bcb6c647a1e9dfec0c3e30c6487aa6c3e5b6b252a847ec510d9c409fa7c9c44f11309

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
